name: Publish
on: push

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # docker login
          docker version
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: docker build
        run: make docker

      - name: docker push
        run: make docker_push

      - name: notify livepeer-infra
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
