name: Tag CI
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v4.20.13

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # docker login
          docker version
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: docker build
        run: make docker

      - name: docker push
        run: make docker_push
